FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /app/src/SocialMedia.WebApi

CMD ["dotnet", "watch", "run", "--no-launch-profile"]