using System;

namespace SocialMedia.Infrastructure.Email;

public static class EmailTemplate
{
    public static string ActivateTemplate(string url, DateTime tokenExpiration) => $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Welcome Page</title>\r\n    <style>\r\n        /* Centering the content in the middle of the page */\r\n        body {{\r\n            display: flex;\r\n            justify-content: center;\r\n            align-items: center;\r\n            height: 100vh;\r\n            margin: 0;\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f4;\r\n        }}\r\n\r\n        /* Centering the content inside the div */\r\n        .content {{\r\n            text-align: center;\r\n        }}\r\n\r\n        /* Styling the h2 element */\r\n        h2 {{\r\n            margin-bottom: 20px;\r\n            color: #333;\r\n        }}\r\n\r\n        /* Styling the link to look like a button */\r\n        .btn {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007BFF;\r\n            color: white;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            transition: background-color 0.3s;\r\n        }}\r\n\r\n        /* Adding hover effect to the button */\r\n        .btn:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n\r\n        /* Styling the paragraph */\r\n        p {{\r\n            margin-top: 15px;\r\n            color: #555;\r\n            font-size: 14px;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n\r\n    <div class=\"content\">\r\n        <h2>Welcome To Exams Platform</h2>\r\n        <a href=\"{url}\" class=\"btn\">Activate</a>\r\n        <p>This link is valid till {tokenExpiration.ToString("G")}.</p>\r\n    </div>\r\n\r\n</body>\r\n</html>\r\n";

    public static string ResetPasswordTemplate(string url, DateTime tokenExpiration) => $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Welcome Page</title>\r\n    <style>\r\n        /* Centering the content in the middle of the page */\r\n        body {{\r\n            display: flex;\r\n            justify-content: center;\r\n            align-items: center;\r\n            height: 100vh;\r\n            margin: 0;\r\n            font-family: Arial, sans-serif;\r\n            background-color: #f4f4f4;\r\n        }}\r\n\r\n        /* Centering the content inside the div */\r\n        .content {{\r\n            text-align: center;\r\n        }}\r\n\r\n        /* Styling the h2 element */\r\n        h2 {{\r\n            margin-bottom: 20px;\r\n            color: #333;\r\n        }}\r\n\r\n        /* Styling the link to look like a button */\r\n        .btn {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007BFF;\r\n            color: white;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            transition: background-color 0.3s;\r\n        }}\r\n\r\n        /* Adding hover effect to the button */\r\n        .btn:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n\r\n        /* Styling the paragraph */\r\n        p {{\r\n            margin-top: 15px;\r\n            color: #555;\r\n            font-size: 14px;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n\r\n    <div class=\"content\">\r\n        <h2>Welcome To Exams Platform</h2>\r\n        <a href=\"{url}\" class=\"btn\">Reset Password</a>\r\n        <p>This link is valid till {tokenExpiration.ToString("G")}.</p>\r\n    </div>\r\n\r\n</body>\r\n</html>\r\n";
}
